import React from 'react'


const goku = () => {
    return (
        <div className='m-auto text-center'>
            <p className='mytext'>ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou ThankYou </p>
        </div>
    )
}

export default goku
